import dagre from "@dagrejs/dagre";

const nodeWidth = 70;
const nodeHeight = 70;

/**
 * 
 * Automatic graph layout from Dagre library
 * 
 * Adapted from the React Flow Dagre example (React Flow, 2026g)

 * using the Dagre Library (Dagre, 2023) 
 * 
 * Creates a graph from passed nodes, edges and direction with new X/Y positions for the nodes
 * 
 * Positions generated by the dagre library
 * 
 * @param nodes array of nodes
 * @param edges array of edges
 * @param direction layout direction e.g. 'LR' for left-to-right
 * @returns nodes with new layout x/y positions and original edges
 */

export default function getLayoutedElements(nodes, edges, direction) {
  const isHorizontal = direction === 'LR';
  const dagreGraph = new dagre.graphlib.Graph().setDefaultEdgeLabel(() => ({}));
  dagreGraph.setGraph({ rankdir: direction });
 
  nodes.forEach((node) => {
    dagreGraph.setNode(node.id, { width: nodeWidth, height: nodeHeight });
  });
 
  edges.forEach((edge) => {
    dagreGraph.setEdge(edge.source, edge.target);
  });
 
  dagre.layout(dagreGraph);
 
  const newNodes = nodes.map((node) => {
    const nodeWithPosition = dagreGraph.node(node.id);
    const newNode = {
      ...node,
      targetPosition: isHorizontal ? 'left' : 'top',
      sourcePosition: isHorizontal ? 'right' : 'bottom',
      position: {
        x: nodeWithPosition.x - nodeWidth / 2,
        y: nodeWithPosition.y - nodeHeight / 2,
      },
    };
 
    return newNode;
    });

    return { nodes: newNodes, edges };
};